version: "3.2"
services:
  web:
    image: nginx
    deploy:
      replicas: 6
      placement:
        max_replicas_per_node: 1
    ports:
     - "8090:80"
    environment:
     - NGINX_HOST=localhost
     - NGINX_PORT=80
